FROM node:22.15.0

WORKDIR /Portfolio

# Copy the pnpm lock file and package.json
COPY pnpm-lock.yaml ./
COPY package*.json ./

# Install pnpm globally and install dependencies
RUN npm install -g pnpm \
    && pnpm install

# Copy the rest of the application code
COPY . .

# Build the TypeScript code
RUN pnpm run build

# Expose the port your API will run on
EXPOSE 8000

# Start the application using pnpm
CMD ["pnpm", "run", "start"]
