# ---------- Build stage ----------
FROM node:22.15.0 AS builder

WORKDIR /Portfolio

COPY pnpm-lock.yaml package*.json ./

RUN npm install -g pnpm && pnpm install

COPY . .
RUN pnpm run build


# ---------- Production stage ----------
FROM nginx:alpine

# Remove default nginx static files
RUN rm -rf /usr/share/nginx/html/*

# Copy built frontend from builder
COPY --from=builder /Portfolio/dist /usr/share/nginx/html

# Expose HTTP port
EXPOSE 80

# Start nginx
CMD ["nginx", "-g", "daemon off;"]
